### ISSUE TITLE
daily post in fediverse

### ISSUE THREAD

**Issue by mega-stoffel** [pietervdvn/MastodonBot#2]
Hej there!
According to your description, you want to post once every month.
But since a few days (August 1st), there's a post every single day from your bot. Did the behavior change or is something broken?
By the way: I prefer the monthly postings.

**Comment by pietervdvn** [comment]
Hi,

I guess you're talking about the [ghost bike bot](https://masto.bike/@ghostbikebot)

Indeed, I misconfigured it, but this is fixed again.
