### ISSUE TITLE
Add instructions to readme on how to get mentioned by the bot

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MastodonBot#3]
also maybe adding a link to the bot account in the readme might be good

**Comment by thibaultmol** [comment]
So it required to have your openstreetmap profile url in your mastodon extra fields?

**Comment by pietervdvn** [comment]
Yes. For example, in [this post](https://en.osm.town/@mapcomplete_edits/113580994098000213) queerthoughts (who has a OSM->Mastodon - link) is not mentioned; as their Mastodon does not link back.

**Comment by pietervdvn** [comment]
(But I'm a bit surprised as well TBH)

**Comment by pietervdvn** [comment]
Actually, no. I'll update

**Comment by thibaultmol** [comment]
I was about to say: I don't think it's realistic to expect that everyone who contributes images via mapcomplete needs to have it in their extra field. Som People already have all there extra fields filled and open street map is not a big enough thing for them to bother putting it in an extra field
